pipeline {
    agent any
	stages{
        stage('Build') {
            steps {
                sh 'cd  simple-java-maven-apps; mvn -B -DskipTests clean package'
            }
        }
		
        stage('Test') {
            steps {
                sh 'cd  simple-java-maven-apps; mvn test'
            }
		
            // post {
            //     always {
            //         junit 'target/surefire-reports/*.xml'
            //     }
            // }
        }
        stage('Deliver') {
            steps {
                sh './demo-class-assets/Jenkins_Pipeline1/scripts/deliver.sh'
            }
        }
		stage('SonarQube Analysis') {
    def mvn = tool 'Default Maven';
    withSonarQubeEnv() {
      sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=simple-java-maven-apps"
    }
  }
	}	
}

