pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Using 'script' block for multiline shell commands
                    sh 'cd simple-java-maven-apps; mvn -B -DskipTests clean package'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'cd simple-java-maven-apps; mvn test'
                }
            }
            // You can uncomment the following block if you want to publish JUnit test results
            // post {
            //     always {
            //         junit 'target/surefire-reports/*.xml'
            //     }
            // }
        }

        stage('Deliver') {
            steps {
                script {
                    sh './demo-class-assets/Jenkins_Pipeline1/scripts/deliver.sh'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    // Navigate to the Maven project directory
                    dir('/devops-training/simple-java-maven-apps/') {
                        // Run Maven commands
                        sh "/usr/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=simple-java-maven-apps"
                    }
                }
            }
        }
    }
}
